### ISSUE TITLE
TwitchApi.V5.Chat.GetAllChatEmoticonsAsync throws BadRequestException

### ISSUE THREAD

**Issue by alex-buraykin** [TwitchLib/TwitchLib.Api#100]
Got an BadRequestException using method ```TwitchApi.V5.Chat.GetAllChatEmoticonsAsync()```

**Update:** if dont push AccessToken (comment line in code), i get result from API. But this result was unable to deserialize:

```
Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'TwitchLib.Api.V5.Models.Chat.EmoticonImage[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'emoticons[0].images.emoticon_set', line 1, position 129.
```

**Update2:** If save response json to file it took ~120Mbytes

**Comment by swiftyspiffy** [comment]
This endpoint looks to be turned off/discontinued. https://api.twitch.tv/kraken/chat/emoticons

Will leave this open until a PR has been merged into to remove the function.

**Comment by Mahsaap** [comment]
manual fetch works fine, looking into this

**Comment by swiftyspiffy** [comment]
Following up on this, I believe it works if you don't set the access token. With that said, v5 is on life support and being turned off in February, so we wont be working on any v5 functionality.
