### ISSUE TITLE
V5.Users.CheckUserSubscriptionByChannelAsync response User property null

### ISSUE THREAD

**Issue by RRickkert** [TwitchLib/TwitchLib.Api#103]
When getting a successful response from V5.Users.CheckUserSubscriptionByChannelAsync, the .User property from the "Subscription" response is null.

The reason: This endpoint has a Channel object instead of a User object in the response instead.
See the difference between: 
* https://dev.twitch.tv/docs/v5/reference/users/#check-user-subscription-by-channel
* https://dev.twitch.tv/docs/v5/reference/channels/#check-channel-subscription-by-user

The same response class is used, hence the .User property is null.

**Comment by Mahsaap** [comment]
This was simlar to GetStream I PR'd the other day. I may fix this one.

**Comment by swiftyspiffy** [comment]
In line with the other v5 endpoint possible issues, I don't think we'll be fixing them because they're being turned off in a few months, and everyone should be using helix at this point.
