### ISSUE TITLE
V5.Users.CheckUserSubscriptionByChannelAsync throws HttpRequestException when token is not from user

### ISSUE THREAD

**Issue by RRickkert** [TwitchLib/TwitchLib.Api#104]
When calling the V5.Users.CheckUserSubscriptionByChannelAsync endpoint, and the token is not from the user, but instead from the channel owner, a HttpRequestException is thrown.

The cause of this is that this specific endpoint is meant for the User to get information about a subscription to a channel, not the other way around.

The response from the API on Twitch's side is a 403 (Forbidden) with the message: "Cannot view user subscription's channel of another user."

Since the HandleWebException in the TwitchHttpClient does not handle 403 return codes, a generic HttpRequestException is thrown instead.
The user gets this error message without any other information on what's going wrong and has no access to the message provided by Twitch.

**Comment by swiftyspiffy** [comment]
Will work on this now.

**Comment by Mahsaap** [comment]
This can be closed
