### ISSUE TITLE
Undocumented.GetChatUserAsync returns null Badges

### ISSUE THREAD

**Issue by benrick** [TwitchLib/TwitchLib.Api#116]
The `Undocumented.GetChatUserAsync` method returns `ChatUserResponse`, which has a `Badges` property of type `KeyValuePair<string,string>`, but that's not the structure returned from the API Call. An array of models in this structure could handle the badge data that *is* returned.

```cs
public class Badge
{
    public string id { get; set; }
    public string version { get; set; }
}
```

**Comment by swiftyspiffy** [comment]
Hey Ben. Sorry about the delay on this. Checking.

**Comment by swiftyspiffy** [comment]
Issue resolved here: https://github.com/TwitchLib/TwitchLib.Api/commit/448b674d4049fd5840d68c0f44b35b9ea955dae3

Thanks for bring this up, and sorry again about the multi-month delay :(
