### ISSUE TITLE
GetUserActiveExtensions - missing parameter

### ISSUE THREAD

**Issue by moritzuehling** [TwitchLib/TwitchLib.Api#129]
Hi there!

According to the [docs](https://dev.twitch.tv/docs/api/reference#get-user-active-extensions), I can ask the extensions for a specific user by supplying the `user_id`:

![image](https://user-images.githubusercontent.com/7847742/71856500-73b2dd00-30e4-11ea-83de-00daac69d235.png)

Unfortunately, TwitchLib doesn't seem to support this, the relevant code seems to be [here](https://github.com/TwitchLib/TwitchLib.Api/blob/24b41a0db37788fc1f6fad89e913f2de94429568/TwitchLib.Api.Helix/Users.cs#L70)

```csharp
        public Task<GetUserActiveExtensionsResponse> GetUserActiveExtensionsAsync(string authToken = null)
        {
            return TwitchGetGenericAsync<GetUserActiveExtensionsResponse>("/users/extensions", ApiVersion.Helix, accessToken: authToken);
        }
```

I think I'll try a PR, as I need that endpoint, but still creating this issue just in case.

**Comment by swiftyspiffy** [comment]
Thanks for bringing this to our attention and the PR. I've gone ahead and merged it into dev. Will close this now.
