### ISSUE TITLE
Helix.Models.Moderation.CheckAutoModStatus.Message Msg_Text needs to be string not bool

### ISSUE THREAD

**Issue by dalhome3** [TwitchLib/TwitchLib.Api#141]
In the message class, the Msg_Text property is a bool whereas it should be a string to pass the text to the auto-moderation API.

https://github.com/TwitchLib/TwitchLib.Api/blob/master/TwitchLib.Api.Helix.Models/Moderation/CheckAutoModStatus/Request/Message.cs

**Comment by Syzuna** [comment]
fixed by #142 

should be available in a few minutes in the latest prerelease version of TwitchLib
