### ISSUE TITLE
Better way of setting Creds for Api

### ISSUE THREAD

**Issue by LuckyNoS7evin** [TwitchLib/TwitchLib.Api#16]
At the moment we have an Initialise Method which sets creds and checks them against the Api

I would like to remove this and instead enable setting of the creds through Api.Settings.ClientId and Api.Settings.AccessToken however include a "CheckCredentials" method which does just that. Returning a KeyValuePair<bool, string>

**Comment by swiftyspiffy** [comment]
I believe this has been completed.
