### ISSUE TITLE
Obtaining an access token requires an access token.

### ISSUE THREAD

**Issue by Tanerax** [TwitchLib/TwitchLib.Api#176]
When attempting to run TwitchLib.Api.V5.Auth.GetAccessTokenFromCodeAsync() it returns an error stating that all requests require an access token, rendering this function kind of pointless

**Comment by Syzuna** [comment]
That check should not be hit by functions that arent Helix Reqests... will investigate

**Comment by Syzuna** [comment]
I have checked the responsible logic for checking if an accesstoken is required and I didnt find any flaws that would lead to your issue. 
Are you able to provide more context?

**Comment by swiftyspiffy** [comment]
Gonna test this real quick.

**Comment by swiftyspiffy** [comment]
Yup, I found the same thing as Syzuna. The request is returning a 400 indicating bad values (code, client id, secret, etc). It does not appear to be enforcing the access token requirement.

Specifically:
```
        internal void ForceAccessTokenAndClientIdForHelix(string clientId, string accessToken, ApiVersion api)
        {
            if (api != ApiVersion.Helix)
                return;
            if (!string.IsNullOrWhiteSpace(clientId) && !string.IsNullOrWhiteSpace(accessToken))
                return;
            throw new ClientIdAndOAuthTokenRequired("As of May 1, all calls to Twitch's Helix API require Client-ID and OAuth access token be set. Example: api.Settings.AccessToken = \"twitch-oauth-access-token-here\"; api.Settings.ClientId = \"twitch-client-id-here\";");
        }
```

Since this is a v5 function, we don't enforce this.

**Comment by swiftyspiffy** [comment]
This should not be an issue. Make sure you're using the latest version.
