### ISSUE TITLE
BadTokenException description is not accurate for ChannelPoints

### ISSUE THREAD

**Issue by billw2012** [TwitchLib/TwitchLib.Api#182]
ChannelPoints endpoints return forbidden if the user is not an affiliate, but this library reports it with BadTokenException and the message:

> The token provided in the request did not match the associated user. Make sure the token you're using is from the resource owner (streamer? viewer?)

If you can't disambiguate between the causes, then making the message include both possibilities would be preferable, so as not to send people on investigations down the wrong path. I remade my token a couple of times, and spent a while trying to work out how this message could be the case before guessing that the message might claim more precise knowledge of the problem than it actually has (I'm not complaining, just relaying my experience; this library and the twitch token generator website are awesome).

**Comment by swiftyspiffy** [comment]
Yea, this is an ugly design decision we made early on that has repeatedly bit us in the ass. In the rewrite of TwitchLib, we're removing the library's attempt to interpret error messages since it's not possible to do accurately and future-proofed. 

Sorry about that :(
