### ISSUE TITLE
JsonSerializationException: A member with the name 'id' already exists

### ISSUE THREAD

**Issue by stephenwelsh** [TwitchLib/TwitchLib.Api#183]
Trying out the new EventSub API (thanks for adding) however getting the following issue when using the "api.Helix.EventSub.GetEventSubSubscriptionsAsync" method.

Newtonsoft.Json.JsonSerializationException: A member with the name 'id' already exists on 'TwitchLib.Api.Helix.Models.EventSub.EventSubSubscription'. Use the JsonPropertyAttribute to specify another name.

It looks like there is a mistake with the JsonProperty for Version:

https://github.com/TwitchLib/TwitchLib.Api/blob/07beee545dcc51a2003304358a85d879a76b69f1/TwitchLib.Api.Helix.Models/EventSub/EventSubSubscription.cs#L14

The 'id' property name is used twice, I guess this needs to be changed to 'version'

**Comment by Mahsaap** [comment]
Thanks , pr to dev #184

**Comment by swiftyspiffy** [comment]
Looks to be resolved. Closing.
