### ISSUE TITLE
Enhancement: Add validation to the CreateEventSubSubscriptionAsync method for the secret argument

### ISSUE THREAD

**Issue by stephenwelsh** [TwitchLib/TwitchLib.Api#185]
For the **CreateEventSubSubscriptionAsync** method:

https://github.com/TwitchLib/TwitchLib.Api/blob/13d8b272684d7279d5eb4bea60bdb9c63016ab71/TwitchLib.Api.Helix/EventSub.cs#L17-L18

The **secret** argument passed to the Twitch EventSub api must be between 10 and 100 characters long, example error response from **https://api.twitch.tv/helix/eventsub/subscriptions**:

``` json
{
  "error": "Bad Request",
  "status": 400,
  "message": "secret must be between 10 and 100 characters"
}
```

However when called with an invalid secret (i.e. too short) it is not very clear as the generic bad Client-Id exception is raised.

I suggest adding an argument validation for the **secret** argument in the  **CreateEventSubSubscriptionAsync** method to alert the caller about the invalid argument, such as:

``` csharp
if(string.IsNullOrEmpty(secret) || secret.Length < 10 || secret.Length > 100) throw new ArgumentException("secret must be between 10 and 100 characters", nameof(secret));
```

**Comment by swiftyspiffy** [comment]
Apologies for the delay, this is addressed in https://github.com/TwitchLib/TwitchLib.Api/pull/233

**Comment by Mahsaap** [comment]
@swiftyspiffy I believe this can be closed.

**Comment by Syzuna** [comment]
Fixed/Changed. Reopen if needed
