### ISSUE TITLE
Cannot Modify Channel Title after updating to latest version

### ISSUE THREAD

**Issue by bilago** [TwitchLib/TwitchLib.Api#205]
`var request = new TwitchLib.Api.Helix.Models.Channels.ModifyChannelInformation.ModifyChannelInformationRequest()`
`            {`
`                Title = title`
`            };`
 `  `          
` await API.V5.Channels.UpdateChannelAsync(id, title);`
           
`await API.Helix.Channels.ModifyChannelInformationAsync(id, request);  `

API.Helix.Channels.ModifyChannelInformationAsync no longer works.

Error:
TwitchLib.Api.Core.Exceptions.BadRequestException: 'Your request failed because either: 
 1. Your ClientID was invalid/not set. 
 2. Your refresh token was invalid. 
 3. You requested a username when the server was expecting a user ID.'

No code changes have been made. I have this set as well:

 `           API.Settings.ClientId = clientID;`
`            API.Settings.AccessToken = token; `

I added
`            await API.V5.Channels.UpdateChannelAsync(id, title);`
as a test, and it updates the stream title without issue, but if I'm not mistaken, V5 is deprecated

**Comment by Syzuna** [comment]
by latest version you mean the latest preview?
this one: https://www.nuget.org/packages/TwitchLib.Api/3.2.4-preview-f4a20c6d848997fa4c8e700eea1c0c6866bba916

bcs there was an issue with the Helix call that should have been fixed in the latest preview

**Comment by Syzuna** [comment]
That fix is now also in the latest stable release for over a month.
If sth is still wrong feel free to reopen.
