### ISSUE TITLE
API.Helix.Streams.ReplaceStreamTagsAsync BadTokenException

### ISSUE THREAD

**Issue by bilago** [TwitchLib/TwitchLib.Api#214]
I'm trying to automatically set my tags when I programmatically update my stream title, but I get a BadTokenException:

`TwitchLib.Api.Core.Exceptions.BadTokenException: 'The token provided in the request did not match the associated user. Make sure the token you're using is from the resource owner (streamer? viewer?)' `

I am definitely using the right token in my API request. Using the same API instance I am also calling 

`Helix.Channels.ModifyChannelInformationAsync` using the same variable for my broadcasterID and it works without issue.

My code is:

        
        List<string> ViewerLevelTags = new List<string>() { "e90b5f6e-4c6e-4003-885b-4d0d5adeb580", "fec05015-e841-4cff-a53c-8aa1336cf863", "6ea6bca4-4712-4ab9-a906-e3336a9d8039"};

        List<string> NonViewerLevelTags = new List<string>() { "e90b5f6e-4c6e-4003-885b-4d0d5adeb580", "6ea6bca4-4712-4ab9-a906-e3336a9d8039"};

        public async Task SetViewerLevelTags()
        {
            await Bot.API.Helix.Streams.ReplaceStreamTagsAsync(Bot.ChannelID, QueueManager.QueueOpen ? ViewerLevelTags : NonViewerLevelTags);
        }

Updating my channel title works fine when called like:

`return await UpdateChannelTitle(Bot.ChannelID, title);`

        public async Task<bool> UpdateChannelTitle(string id, string title)
        {  
            try
            {
                var request = new TwitchLib.Api.Helix.Models.Channels.ModifyChannelInformation.ModifyChannelInformationRequest()
                {
                    Title = title
                };
                await Bot.API.Helix.Channels.ModifyChannelInformationAsync(id, request);
                await SendMessage($"Title has been updated to: {title}");
                return true;
            }
            catch (Exception e)
            {
                await Logging.Write(e.Message, Logging.Severity.Error);
                await SendMessage($"Could not update the stream title! Sorry bilagoOOF");
                return false;
            }
        }

**Comment by bilago** [comment]
Just an update with more info, I generated a new Token that includes every scope, including:

` channel:manage:broadcast | Manage your channel's broadcast configuration, including updating channel configuration and managing stream markers and stream tags. `

and it still does not work, but I can update the channel title.

**Comment by swiftyspiffy** [comment]
Will look into this when I get home in a few hours.

**Comment by swiftyspiffy** [comment]
Also can you confirm that either you're using the dev branch, or you're using the latest prerelease of the package from NuGet?

**Comment by bilago** [comment]
> Also can you confirm that either you're using the dev branch, or you're using the latest prerelease of the package from NuGet?

I'm using:

3.2.5-preview-9a3c9a73b72f479e1c27fec4e1c7ec77dd69f125

**Comment by Syzuna** [comment]
those exceptions only get thrown based on statuscodes we get back so that makes it even more intresting

**Comment by Mahsaap** [comment]
May i ask what tags those are? The reason im asking is this: 
`NOTE: You may not specify automatic tags; the call will fail if you specify automatic tags. Automatic tags are tags that Twitch applies to the channel. For a list of automatic tags, see List of All Tags. To get the list programmatically, see Get All Stream Tags.`
https://dev.twitch.tv/docs/api/reference#replace-stream-tags

**Comment by Syzuna** [comment]
Based on @Mahsaap theory I looked up the tags you are setting and 6ea6bca4-4712-4ab9-a906-e3336a9d8039 is the id for "English" which seems to be an automatic tag that you cant set via API, maybe omit it and try again.

**Comment by bilago** [comment]
> Based on @Mahsaap theory I looked up the tags you are setting and 6ea6bca4-4712-4ab9-a906-e3336a9d8039 is the id for "English" which is an automatic tag that you cant set via API. Omit it and try again.

That was the problem, removed that tag from the list and it now sets them properly. Thank you @Mahsaap and @Syzuna
