### ISSUE TITLE
Helix.Users.DeleteUserFollows is depreciated

### ISSUE THREAD

**Issue by FusionBreak** [TwitchLib/TwitchLib.Api#232]
Since July 27, 2021 the endpoints for Follow Channel, Unfollow Channel, Create User Follows and Delete User Follows have been shut down. Therefore, using them will result in a TwitchLib.Api.Core.Exceptions.BadScopeException.
Source: https://discuss.dev.twitch.tv/t/deprecation-of-create-and-delete-follows-api-endpoints/32351

**Comment by swiftyspiffy** [comment]
These were actually recently deleted from the dev branch: https://github.com/TwitchLib/TwitchLib.Api/commit/d940a8201a2a22b29dccb6630092fb3e345b958f . Let me know if there's still confusion.
