### ISSUE TITLE
GetStreamsMetaData was deprecated, missed and needs to be removed.

### ISSUE THREAD

**Issue by Mahsaap** [TwitchLib/TwitchLib.Api#238]
https://discuss.dev.twitch.tv/t/deprecation-of-the-helix-get-streams-metadata-endpoint/26407

Refer to this issue as well https://github.com/TwitchLib/TwitchLib/issues/1065

**Comment by swiftyspiffy** [comment]
GetStreamsMetadata has been removed :)
