### ISSUE TITLE
user:read:follows missing in scopes

### ISSUE THREAD

**Issue by breadbyte** [TwitchLib/TwitchLib.Api#251]
The `user:read:follows` scope is required for [Helix/Streams/Followed](https://dev.twitch.tv/docs/api/reference#get-followed-streams)
for the api call [API.Helix.Streams.GetFollowedStreamsAsync](https://github.com/TwitchLib/TwitchLib.Api/blob/master/TwitchLib.Api.Helix/Streams.cs#L121)
and it seems to be missing from the scopes enum.

**Comment by Syzuna** [comment]
Is that Enum even used for anything anymore internally?
Will check

**Comment by Syzuna** [comment]
oh it actually is.

**Comment by breadbyte** [comment]
I used it in calling `API.Auth.GetAuthorizationCodeUrl`.

**Comment by Syzuna** [comment]
Yeah saw that as well.
Will review the enum for any missing ones and add them in a second.

**Comment by Syzuna** [comment]
We are actually missing quite a lot in there

**Comment by Syzuna** [comment]
hotfix version 3.4.1 that contains a lot of new scopes should be showing up in nuget in a few minutes.

**Comment by breadbyte** [comment]
3.4.1 is live on nuget now with the updated enums. Thank you!
