### ISSUE TITLE
Is_paused missing from updatecustomreward model

### ISSUE THREAD

**Issue by Mahsaap** [TwitchLib/TwitchLib.Api#253]
Is_paused missing from updatecustomreward model
As mentioned in discord.

**Comment by Mahsaap** [comment]
https://github.com/TwitchLib/TwitchLib.Api/blob/dev/TwitchLib.Api.Helix.Models/ChannelPoints/UpdateCustomReward/UpdateCustomRewardRequest.cs

**Comment by Mahsaap** [comment]
https://dev.twitch.tv/docs/api/reference#update-custom-reward

**Comment by swiftyspiffy** [comment]
Fixed with above merge.
