### ISSUE TITLE
[Bug] LiveMonitor not raising Stream Live Event

### ISSUE THREAD

**Issue by SFFan123** [TwitchLib/TwitchLib.Api#262]
In the Nuget Verions below the LiveMonitor does not raise the stream is live event (OnStreamOnline never gets triggered). But it works in earlier versions.

Used Sample code to verify. Also verified that Monitor.OnServiceTick is fired.

Doesn't work in version:
- 3.5.0

Works in Versions:
- 3.4.1
- 3.4.0
- 3.3.0

**Comment by MrLawbreaker** [comment]
Calling UpdateLiveStreamersAsync of the Monitor directly results in an Auth Exception "(A Client-Id and OAuth token is required to use the Twitch API)"

I provide the API with ClientSecret and ClientID this worked in previos versions but not in 3.5

**Comment by credfeto** [comment]
Having same issue - updating to pre-release ``3.5.1-preview-454bf266f3d74f6f43f2381dea7ffa8d35c13646`` nuget package stops the exception.

**Comment by SFFan123** [comment]
Seems to be fixed in release [3.5.2](https://www.nuget.org/packages/TwitchLib.Api/3.5.2)
