### ISSUE TITLE
GetPlaylistAsync Returns no Information abot Tracks in the Playlist (null)

### ISSUE THREAD

**Issue by Dukmos** [TwitchLib/TwitchLib.Api#271]
The **PlaylistTrack** Model contains a Property called **CatalogTracks** that maps to a API Response **catalog_tracks**.

But in the actual Twitch API the Property is called **tracks**

see Twich Docs: [https://dev.twitch.tv/docs/api/reference#get-soundtrack-playlist](https://dev.twitch.tv/docs/api/reference#get-soundtrack-playlist)

**Comment by Dukmos** [comment]
turns out they changed the Data Structure again on June 27th . This time a bigger Breaking change.
see update in the Docs: https://dev.twitch.tv/docs/api/reference#get-soundtrack-playlist

they now only Return a `Track[]` as **data** and a **pagination** object which means there are 2 new Parameter
- **after**
- **first** (Docs say the max is 100, but API enforces max 50 in my test)

and the following Properties were removed
- description
- id
- image_url
- title

there are also changes to `GetPlaylits`
see the Docs: https://dev.twitch.tv/docs/api/reference#get-soundtrack-playlists

- it supports an **id** Parameter to get info on one Playlist (to get the Infos they removed from the other endpoint)
- and it now also supports pagination
   - **after** Parameter
   - **first** Parameter (has to be 50 or lower acording to API, is not mentioned in the Docs for now)

**Comment by Mahsaap** [comment]
Thank you going to try and add this.

**Comment by Mahsaap** [comment]
I did not see pagination on GetPlaylists.
![image](https://user-images.githubusercontent.com/13688718/176811679-803421bb-7c0d-48bd-a3f0-9e0095b552d6.png)

**Comment by Mahsaap** [comment]
however get playlist does and that was added

**Comment by Dukmos** [comment]
Oh, i meant that it is not mentioned in the Docs, but the API still returns a `pagination` object in the Response
![image](https://user-images.githubusercontent.com/1273625/176938031-5d84b6e1-d689-400d-90f8-904334607258.png)

and it also reacts to the pagination Parameters (there seems to be 60 Playlists atm)
![image](https://user-images.githubusercontent.com/1273625/176938327-94023a5f-5c8d-4799-b4d6-44b525c01ab3.png)
![image](https://user-images.githubusercontent.com/1273625/176938968-23669823-a99e-4237-9485-11a39bb60711.png)

but `first` is only allowed to be 50 and below
![image](https://user-images.githubusercontent.com/1273625/176938525-eaf72011-3167-44ab-95ce-9e4beb638a1e.png)

and for the `Playlist` Endpoint: differently from the Docs the API enforces a maximum of 50 for first
![image](https://user-images.githubusercontent.com/1273625/176939311-0fdb622d-008a-4e5e-bb2f-07546d7d7246.png)

as this behaviour is different from the Docs, im not sure if you want to use it, but for completion sake here the screens from my test. sorry for not including them in the report yesterday. it was way to late for me when i noticed this and i wanted to complete it before falling asleep.

**Comment by Mahsaap** [comment]
Oh ok thanks. I'll see what others want to do. Docs tend to have issues anyway. Thanks for the info.

**Comment by Mahsaap** [comment]
They are calls in beta, they are likely to change a bit more as well. According to docs anyway

**Comment by Dukmos** [comment]
agree. just for good measures i also put in a issue about the Doc mismatch the official way, so they can decide what to do
twitchdev/issues#627

**Comment by Syzuna** [comment]
Fixed
