### ISSUE TITLE
More error feedback from the API

### ISSUE THREAD

**Issue by BhaaLseN** [TwitchLib/TwitchLib.Api#275]
I'd like get some more info when calls fail, especially when the error response from Twitch includes a specific reason.
[`TwitchWebRequest.HandleWebException`](https://github.com/TwitchLib/TwitchLib.Api/blob/master/TwitchLib.Api.Core/HttpCallHandlers/TwitchWebRequest.cs#L116) is nice, and attempts to make things a bit more streamlined (which is generally fine), but I ran into a parameter issue the other day that took me way longer to debug than I wanted.

Just to give a quick rundown of what happened to me:
1. I tried to interact with a channel that didn't match the OAuth token (which resulted in a 400 Bad Request)
2. `TwitchWebRequest.HandleWebException` turns this into a `BadRequestException`, asking me politely to check my ClientID, my refresh token and whether I mistakenly passed a user name instead of the id.
3. After verifying multiple times they should be fine, I tinkered with Fiddler since everything is HTTPS and I had to let it break things open first.
4. After Fiddler was successfully capturing my API traffic, the response clearly stated that "the passed `broadcaster_id` does not match the user from the OAuth token".

With that, I could finally get my parameters in order; but the steps involved into this were much more convoluted than they could've been.

My proposal would either be a simple `string` property on the custom exceptions that contains the API response text, or alternatively including the original exception as `InnerException`. Or maybe even both.

Depending on whether you're worried about exposing potentially sensitive data with that (or not), I can also live with hiding this behind a developer option (that needs to be toggled on at runtime).

**Comment by BhaaLseN** [comment]
Basically #265, but this doesn't seem to be getting anywhere.

**Comment by Mahsaap** [comment]
Thx for bringing it up again. I think we're going to look at adding this. Probably just missed , people have been busy for a while. The previous pr is likely going to need to be updated for latest dev branch. I may look at doing this later so it's ready if one of them decide to merge it. Cheers.

**Comment by Mahsaap** [comment]
Merged
