### ISSUE TITLE
GetStreamsAsync not returning any streams

### ISSUE THREAD

**Issue by Chris-Is-Awesome** [TwitchLib/TwitchLib.Api#284]
I'm trying to check if my channel is live, not sure if there's something I'm missing or what.
```csharp
public async Task<bool> AmILive()
{
	var response = await api.Helix.Streams.GetStreamsAsync(userIds: new List<string> { ChannelId });
	// response.Streams.Length always returns 0
	return response.Streams[0].Type == "live";
}
```

I've verified the ChannelId is correct, along with clientID and accessToken passed to the API settings. I've been using other Helix endpoints just fine but this one fails to return my stream, but can return others.

I've also tried using my login name and that also doesn't work.
Looked at some examples of other uses of it and didn't see any difference from mine.

Could it be that I'm missing some scopes for it? It's been quite some time since I touched the scopes so not sure if there's something I skipped there.

**Comment by Mahsaap** [comment]
It's null if the channel is offline

**Comment by Chris-Is-Awesome** [comment]
> The object is null if the channel is offline. So Stream list will be length of 0 when offline.
> 
> If your going live with your channel to test it , keep on mind it can take some time for the API to see your online.

Oh that makes sense, thanks!
