### ISSUE TITLE
Missing Helix API to Get, Add and Remove VIPs

### ISSUE THREAD

**Issue by NephChevsky** [TwitchLib/TwitchLib.Api#285]
Hello,

The TwitchLib Api seems to be missing Helix endpoints for channel's VIPs

https://dev.twitch.tv/docs/api/reference#get-vips
https://dev.twitch.tv/docs/api/reference#add-channel-vip
https://dev.twitch.tv/docs/api/reference#remove-channel-vip

If you find the time to add it some day
Thank you in advance!

**Comment by Mahsaap** [comment]
#281

**Comment by NephChevsky** [comment]
Merged in 3.6.1
