### ISSUE TITLE
Calling Helix.Soundtrack.GetPlaylistsAsync without ID throws exception

### ISSUE THREAD

**Issue by Dukmos** [TwitchLib/TwitchLib.Api#288]
Calling Helix.Soundtrack.GetPlaylistsAsync without ID Parameter to get all playlists throws exception when trying to urlencode null

![image](https://user-images.githubusercontent.com/1273625/183718884-0daead82-472f-4a60-b8f2-c879c2690c64.png)

I Believe the culprit is Line 78 here, always adding the id to the Params List. There is already a check a few lines later that only adds it when ist not null
https://github.com/TwitchLib/TwitchLib.Api/blob/2d5955151f96ab1ab4f5b6d13c259c37c5df0455/TwitchLib.Api.Helix/Soundtrack.cs#L63-L89

Workaround for now is adding an empty string as id parameter.

**Comment by Syzuna** [comment]
a release with a fix should be on nuget shortly.
thanks for flagging it!
