### ISSUE TITLE
Property Color of UserChatColorResponseModel is bool, it should be string

### ISSUE THREAD

**Issue by DustOneHub** [TwitchLib/TwitchLib.Api#290]
![bool Color](https://user-images.githubusercontent.com/39590649/186142487-6e05c374-5762-48c0-a381-a511c6522973.PNG)

The Property _Color_ in _UserChatColorResponseModel_ is of Type _bool_. It should be of Type _string_.

**Comment by Mahsaap** [comment]
Thx likely from me doing a copy paste

**Comment by Syzuna** [comment]
Fixed
