### ISSUE TITLE
Badges.v5.GetGlobalBadgesAsync() not working

### ISSUE THREAD

**Issue by RickRosendaal** [TwitchLib/TwitchLib.Api#31]
There is a typo in the Badges.v5.GetGlobalBadgesAsync() function: 

"/v1/badges/**gloal**/display"
instead of
"/v1/badges/**global**/display"

**Comment by swiftyspiffy** [comment]
Looking into this, thanks :)

**Comment by swiftyspiffy** [comment]
Should be fixed now.
