### ISSUE TITLE
Auth is not available from ITwitchApi

### ISSUE THREAD

**Issue by HencoDesu** [TwitchLib/TwitchLib.Api#331]
TwitchApi class has a Auth property
https://github.com/TwitchLib/TwitchLib.Api/blob/4f70cfa4ed526447e5cdf0e4ea6997d92dbd7994/TwitchLib.Api/TwitchAPI.cs#L16

But in ITwitchApi this property is missing. Is there any reason for this from design side or just a miss?

**Comment by Mahsaap** [comment]
Probably missed

**Comment by Mahsaap** [comment]
actually its already added in teh dev branch and should be part of pre release
