### ISSUE TITLE
Error with GetBannedUsers

### ISSUE THREAD

**Issue by nexxecho** [TwitchLib/TwitchLib.Api#333]
I'm getting an error when calling GetBannedUserAsync when broadcaster ID and moderator ID are not the same. The moderator has access to moderate and is an editor for the broadcaster.

> Unhandled exception: TwitchLib.Api.Core.Exceptions.BadScopeException: Your request was blocked due to bad credentials (Do you have the right scope for your access token?).

```
foreach (User broadcaster in broadcasterList)
{
    Console.WriteLine($"Trying to ban {user.DisplayName} for {broadcaster.DisplayName}");
    GetBannedUsersResponse bannedUsers = await API.Helix.Moderation.GetBannedUsersAsync(broadcaster.Id, new List<string> { user.Id });

    if (bannedUsers.Data.Any())
    {
        BanUserResponse banResponse = await API.Helix.Moderation.BanUserAsync(broadcaster.Id, Settings.ModeratorID, banRequest);
        Console.WriteLine($"{user.DisplayName} banned in {broadcaster.DisplayName} with reason: {reason}");
    }
}
```

![0jHPxgCLJD](https://user-images.githubusercontent.com/96966132/210283590-a8da99e6-2064-4252-9d59-c704427e6749.png)

**Comment by Syzuna** [comment]
That response from Twitch is to be expected.
Sadly that endpoint only works for the broadcaster itself.
That means you need a token from the broadcaster with the appropiate scopes.

For more info see <https://dev.twitch.tv/docs/api/reference#get-banned-users>
Especially the description of the broadcaster_id param: "The ID of the broadcaster whose list of banned users you want to get. **This ID must match the user ID in the access token.**"

**Comment by nexxecho** [comment]
Ok thank you I missed that part in the documentation.
