### ISSUE TITLE
API GetChattersAsync always returns BadTokenException

### ISSUE THREAD

**Issue by xDeveluxe** [TwitchLib/TwitchLib.Api#343]
Hello.

I am sorry if thats not the right way to open an issue, but I will try my best to describe a problem.

Building bot on C#, both Client and API works ok, but not API.Helix.Chat.GetChattersAsync.
API calls with creating clip or getting follower data, or getting any other data works as intended, but not mentioned function.
For some reason GetChattersAsync always returns me BadTokenException with this information:
The token provided in the request did not match the associated user. Make sure the token you're using is from the resource owner (streamer? viewer?)

Im pretty much sure I set it up correctly, since in my code
BroadcasterId is user id, which is associated with stream I want to get chatters from.
ModeratorId is user (bot) id, which is associated with access token for sure.
Is there my mistake or is this just bugged?
Thank you in advance.

Code:
![image](https://user-images.githubusercontent.com/102395107/219902781-7d74d2da-1602-47a2-95bc-2a45ea033d9f.png)

Exception:
![image](https://user-images.githubusercontent.com/102395107/219902806-0f300fc3-b75f-4ca9-a806-b9968f734250.png)

**Comment by Mahsaap** [comment]
Make sure you have the scope required and the token being used pairs with the moderatorid. 

https://dev.twitch.tv/docs/api/reference/#get-chatters

**Comment by xDeveluxe** [comment]
I have the scope required (moderator:read:chatters) and Config.BotId is id of bot-user, which is paired to access token, that API uses.

**Comment by Mahsaap** [comment]
The bot is moderator in the channel? I'm assuming it is but just making not it does need to be a user token.

**Comment by xDeveluxe** [comment]
Bot is also moderator on the Config.StreamerChannelId user channel. 
Its like Im missing something important or idk. Does it work for you? If yes, I will continue to workaround on my code tomorrow.

**Comment by Mahsaap** [comment]
I asked soemome to test. I'm not near PC ATM.

**Comment by xDeveluxe** [comment]
Thank you, will be glad to hear if it works if somebody tests this as well.

**Comment by Syzuna** [comment]
Hey,
sorry just got to testing this now and I am not able to reproduce it with TwitchLib.Api Version 3.8.0
I've tested it with the broadcaster being the same as token owner and also tested the token owner being a mod of the broadcaster and both requests ran fine.
Is there any more info you can provide?

**Comment by xDeveluxe** [comment]
I am using TwitchLib 3.5.3, should I swap from using TwitchLib to TwitchLib.Client and TwitchLib.Api latest versions?

**Comment by Mahsaap** [comment]
Suite 3.5.3 uses 3.8.0 api
https://www.nuget.org/packages/TwitchLib#dependencies-body-tab

**Comment by xDeveluxe** [comment]
Then Im out of ideas, to be honest. 
But since its working for you, then its on my side. 
Dont know where, but will try to find, thank you for testing it out!

**Comment by Mahsaap** [comment]
This might seem redundant but can you try adding the  bots access token to the calls as well.

**Comment by xDeveluxe** [comment]
Will try it out, thanks. But I dont expect it to work, haha :D

**Comment by xDeveluxe** [comment]
Problem solved somehow by itself, even without adding an access token to function.
Now its working correctly, giving back the list. Magic :D
