### ISSUE TITLE
Get Channel Followers

### ISSUE THREAD

**Issue by da66en** [TwitchLib/TwitchLib.Api#369]
GetUsersFollowsAsync() is using an endpoint that has been removed.

They have added https://api.twitch.tv/helix/channels/followers as a replacement.

I don't see this being used in the API?

https://dev.twitch.tv/docs/api/reference/#get-channel-followers

**Comment by iProdigy** [comment]
The replacement, `GetChannelFollowersAsync`, is already implemented: https://github.com/TwitchLib/TwitchLib.Api/blob/8e57e964e6c1030378da16ab1b2c34f06d245a1e/TwitchLib.Api.Helix/Channels.cs#L256

**Comment by da66en** [comment]
Thanks - you're right, I was looking in the wrong spot.
Closing this.
