### ISSUE TITLE
Not Compatible with Visual Basic

### ISSUE THREAD

**Issue by swiftyspiffy** [TwitchLib/TwitchLib.Api#37]
_From @mbfan on April 27, 2018 17:22_

Hello,
please consider rewriting the Code to remove all duplication of Members. Visual Basic ignores upper and lower case, and i can't use any method cause there is (for example) a "v5" and a "V5", which are the same to VB.
With kind regards,
Nico

_Copied from original issue: TwitchLib/TwitchLib#394_

**Comment by swiftyspiffy** [comment]
_From @LuckyNoS7evin on April 27, 2018 17:30_

@mbfan thanks, we do know about this, I believe there was a discussion early to mid 2017 with regards to this and it was a decision to just support c# only. (Forgive me if I'm wrong it was just as I started using TwitchLib and wasn't a large contributor like now)

As we are always working on the library and with the removal of both v3 and v5 at the end of 2018 this may be a time we become compatible with VB again

**Comment by swiftyspiffy** [comment]
_From @mbfan on April 27, 2018 17:34_

Hello,
then you should at least remove the hint that it's compatible with Visual Basic in the Readme ;)
The problem occurs with Helix/helix too.
Nico

**Comment by swiftyspiffy** [comment]
_From @LuckyNoS7evin on April 27, 2018 17:36_

Ah, missed a bit, thanks

**Comment by swiftyspiffy** [comment]
_From @mbfan on April 27, 2018 17:38_

It would help too moving the "Sub-Classes", for example in "ThirdParty", into another Namespace, if possible.

**Comment by swiftyspiffy** [comment]
_From @Syzuna on April 27, 2018 17:47_

As most of us here are only on the C# side of things, how would moving classes to different namespaces help?

**Comment by swiftyspiffy** [comment]
_From @mbfan on April 27, 2018 17:54_

The Problem is the Duplication of "v5"/"V5" for Visual Basic, cause it doesnt work Casesensitive. But if the Classes would be in a different Namespace, say "TwitchLib.API.Sections.Classes", there wouldn't be such a duplication inside the same Class.

**Comment by swiftyspiffy** [comment]
If I understand this correctly, it only seems to affect the API component of the library right? I think we can definitely work towards a solution here with some renaming of classes.

**Comment by swiftyspiffy** [comment]
_From @mbfan on April 27, 2018 19:20_

As far as I have discovered it, yes.

**Comment by swiftyspiffy** [comment]
_From @Mahsaap on May 1, 2018 12:38_

As a note, a comment was added to the readme that states not supporting API in VB currently.

**Comment by Mahsaap** [comment]
@mbfan we have updated api for vb. Hope this fixes the issue.

**Comment by swiftyspiffy** [comment]
Will go ahead and close this, feel free to reopen as necessary.
