### ISSUE TITLE
Calling TwitchLib.Api.Auth.GetAccessTokenFromCodeAsync returns "NullReferenceException" before calling ".Result"

### ISSUE THREAD

**Issue by WrithemTwine** [TwitchLib/TwitchLib.Api#381]
Working on an Authentication Code grant flow.

Finding issue at this method:
https://github.com/TwitchLib/TwitchLib.Api/blob/master/TwitchLib.Api/Auth/Auth.cs#L91C55-L91C55
with these versions in my solution:
![image](https://github.com/TwitchLib/TwitchLib.Api/assets/20450441/5c33a211-252c-476f-9bc5-593ea1462756)

source: https://github.com/WrithemTwine/TwineChatBot/blob/Twitch_RenewToken/StreamerBotLib/BotClients/Twitch/TwitchTokenBot.cs#L131
Testing:
I have the "Client Id", "Client Secret", and an "auth code" (the Auth Code URL method) available for the GetAccessTokenFromCodeAsync arguments. I tried an empty/null "ApiSettings" and tried "ApiSettings" with "clientID and secret" (current code version in the repo) but not 'scopes' because I have a string 'scopes' version (I converted it into a URL query string safe value for the auth-url call) instead of the AuthScopes enum version (List<_AuthScopes enum_> required for ApiSettings.Scopes); and I get the same result in both 'apisettings' cases. The task status is faulted (breakpoint at the method call) before calling "(Task).Result" to access the 'AuthCodeResponse' object.
![image](https://github.com/TwitchLib/TwitchLib.Api/assets/20450441/33c25fbf-04d4-4966-a907-e3537138282d)

My code permits a user to use a bot chat account and a broadcast clientID/token (both a static 60-day token set and now the auth code token set), if the user wants to separate and have the bot account chat into the channel chat; use the streamer token to access broadcaster level API data. That's why code has some "duplicate" looking code calls, but different between 'bot' and 'streamer' in the object names. (I had static token process setup first, and adapted code to switch off between static token and this new auth code process - some code might be a touch messy = possible future rewrite for cleanup).

actual TwitchLib call: https://github.com/WrithemTwine/TwineChatBot/blob/Twitch_RenewToken/StreamerBotLib/BotClients/Twitch/TwitchTokenBot.cs#L238
By all indications, the authentication try stops at "AuthBot.GetAccessTokenFromCodeAsync(...).Result"; with the NullReferenceException and unable to retrieve the 'access' and 'refresh' tokens.

Any ideas? Anyone else have success, where this code fails in my case and scenario?
Is the 'AuthScope' list explicitly required (apisettings) for the further internal TwitchLib calls? I mean, I have a space-delimited text string of the scopes, not in enum format (yet).

**Comment by WrithemTwine** [comment]
Tested with an enum scope added to List<_AuthScopes_> in apisettings & also associated with the auth code, and still received NullReferenceException.

simple project code (just testing Auth Code & refresh/access tokens): 
https://github.com/WrithemTwine/TwineChatBot/tree/a0371f151b970db9284dd84ac1f086cd05d8f3a6/SimpleTestFeature

Just download, build & run, add the client Id & client secret, and click the buttons (auth code first).

![image](https://github.com/TwitchLib/TwitchLib.Api/assets/20450441/4cf41f66-df2f-47bf-bdd2-b6b6748d27a0)

**Comment by WrithemTwine** [comment]
Solved what caused the issue:

ApiSettings apiSettings = new();
AuthBot = new Auth(apiSettings, new BypassLimiter(), new TwitchHttpClient(null));

The TwitchLib.Api.Auth constructor requires all objects instead of using a default if passed 'null', e.g. "Auth(apiSettings, null, null)". The "NullReferenceException" occurred from a null "IRateLimiter" and null "IHttpClientHandler" passed to the constructor.

This could be remedied through a constructor update to handle null parameters, or add a note in the Auth() documentation, or something else. Ideally, I believe adding null default parameters and handling them in the constructor would be cleaner.

**Comment by LuckyNoS7evin** [comment]
This is around dependency injection and having defaults and how the README.md for twitch API says to do `var api = new TwitchAPI();` this is due to it creating the defaults for you and the rest of an API instance so you can do the calls you need rather than using "just" the auth side of things.

[https://github.com/TwitchLib/TwitchLib.Api/blob/master/README.md](https://github.com/TwitchLib/TwitchLib.Api/blob/master/README.md)

**Comment by WrithemTwine** [comment]
Thanks for the info. Looks like it can be closed. 

If it doesn't appear useful, go ahead and delete or I can give it a try.
