### ISSUE TITLE
Missing new endpoints

### ISSUE THREAD

**Issue by betrayedjinn** [TwitchLib/TwitchLib.Api#387]
Twitch has several endpoints marked as "new" that are not included in this lib.
https://dev.twitch.tv/docs/api/reference/#send-chat-message

Can someone please add them?

**Comment by Mahsaap** [comment]
https://github.com/TwitchLib/TwitchLib.Api/blob/45e39dbc2d3b329badb2ab34087d9ff642e59e13/TwitchLib.Api.Helix/Chat.cs#L310

It is on dev branch, not merged to master yet.
