### ISSUE TITLE
Bits.helix.GetBitsLeaderboardAsync throws NullReferenceException

### ISSUE THREAD

**Issue by Anton0123** [TwitchLib/TwitchLib.Api#39]
I've initialized the client and set the accesstoken and clientid but when using the command ` TwitchAPI.Bits.helix.GetBitsLeaderboardAsync(1, TwitchLib.Api.Enums.BitsLeaderboardPeriodEnum.Week);` I get a System.NullReferenceException from TwitchLib.Api.ApiSettings,DynamicScopeValidation.

EDIT: To make it clear, I don't call it like a static function in the actual code

**Comment by Syzuna** [comment]
whats your version?

The scope validation bug should be fixed since a while already.
Maybe its a new one tho just want to make sure.

**Comment by Syzuna** [comment]
Nice that you got it working :)
