### ISSUE TITLE
RefreshResponse ExpiresIn is always 0

### ISSUE THREAD

**Issue by D3adL0ck** [TwitchLib/TwitchLib.Api#45]
Hey, I am using the following code on the latest lib version (2.1.4)

`                        
var authToken = TwitchApi.Auth.v5.RefreshAuthTokenAsync(refreshToken, clientSecret).GetAwaiter().GetResult();
`

And the response it gives always have the ExpiresIn field set to 0.

**Comment by swiftyspiffy** [comment]
Testing now.

**Comment by swiftyspiffy** [comment]
I think this is an error in the model. There shouldn't be an ExpiresIn value for a refresh request: https://dev.twitch.tv/docs/authentication/#refreshing-access-tokens

**Comment by swiftyspiffy** [comment]
After talking to @Syzuna and @Mahsaap it looks like only legacy Client IDs are allowed to generate unlimited duration access tokens. In this case, Twitch doesn't return an expires_in field, leading the model to populate with a defaulted 0 value. If create a new app on dev.twitch.tv, and use the client id, refresh token, and secret from that, you'd get an expires_in value I think.

So I think the library is indeed working as expected. Feel free to reopen as needed.
