### ISSUE TITLE
[Broke]{Dev Branch} Helix change for the monitor broken

### ISSUE THREAD

**Issue by Mahsaap** [TwitchLib/TwitchLib.Api#69]
Not sure how I missed this but its not triggering event on detecting a channel online. It does however detect the online channels correctly in the library code. `GetLiveStreamersAsync` works. Its `CheckForOnlineStreamChangesAsync` not working atm.

I'm still investigating, but to ensure the lib is not pushed to nuget or to master till this is fixed, I'm adding this issue.

**Comment by Mahsaap** [comment]
var currentStream = liveStreamers.FirstOrDefault(x => x.UserId == channel);

not working, when userid and channel match, currentstream is not set and remains null

**Comment by RRickkert** [comment]
Could you provide the code that you've used to try this out? It all seems to work perfectly fine for me. @Mahsaap

**Comment by Mahsaap** [comment]
Fixed in #70

**Comment by swiftyspiffy** [comment]
This has presumably been fixed with the merge
