### ISSUE TITLE
Add Get Id Examples

### ISSUE THREAD

**Issue by Mahsaap** [TwitchLib/TwitchLib.Api#91]
Many seem to ask, so good to have.

```
//V5
var user = await api.V5.Users.GetUserByNameAsync("ChannelName");
```

**Comment by Teravus** [comment]
The only other thing that I would add to this is...  you need to create an instance of TwitchLib.Api.TwitchAPI prior to using these API calls.  When I first started using the library, I got hung up on this.

var api = new TwitchLib.Api.TwitchAPI();

The parameterless constructor works.  The other optional parameters look like they are mostly for passing in mockup objects for testing.

**Comment by demortes** [comment]
This is now redundant and can probably be closed. V5 no longer has support and will be shut down on Feb 2022.

**Comment by swiftyspiffy** [comment]
Yup, good call! Will close this.
